=== rjb4standards/REA-Products/SAGVendorSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:SAG="http://softwareassuranceguardian.com/"  
		elementFormDefault="qualified" 
		targetNamespace="http://softwareassuranceguardian.com/" 
		version="1.1.4">
<!-- Copyright and all other rights reserved by Reliable Energy Analytics, LLC 2018-2021. Licensed under Creative Commons 4.0 https://creativecommons.org/licenses/by/4.0/  --> 
  

    <element name="VendorResponse" type="SAG:VendorResponsetype"></element>

    <complexType name="VendorResponsetype">
    	<sequence>
    		<element name="VendorLegalName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="SupplierID" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="StreetAddress" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="City" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="StateOrProvince" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ZipCode" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Country" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="WebsiteURL" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ContactTelephone" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ContactEmail" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ContactPerson" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="DUNSNumber" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="NAESBEIRID" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>

    		<element name="CyberSecPolicyURL" type="string"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="FinancialDataURL" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="CompanyDataURL" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Products" type="SAG:Products" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>



    <complexType name="ProductType">
    	<sequence>
    		<element name="LicensorName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ProductName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Version" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="SBOM" type="SAG:SBOMType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="SourceLocationURL" type="string"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="DigitallySigned" maxOccurs="1"
    			minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Y"></enumeration>
    					<enumeration value="N"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="UnsolvedVulnerabilities" maxOccurs="1"
    			minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Y"></enumeration>
    					<enumeration value="N"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="SDLCPolicyURL" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="SDLCEvidenceDataURL" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="CommercialStatus" maxOccurs="1"
    			minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Available"></enumeration>
    					<enumeration value="Retired"></enumeration>
    					<enumeration value="EOL"></enumeration>
    					<enumeration value="BetaTest"></enumeration>
    					<enumeration value="Pilot"></enumeration>
    					<enumeration value="Abandoned"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="SupportStatus" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Supported"></enumeration>
    					<enumeration value="Unsupported"></enumeration>
    					<enumeration value="Community"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="LastModifiedDateTimeUTC" type="dateTime"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>

    </complexType>

  
    <complexType name="Products">
    	<sequence>
    		<element name="Product" type="SAG:ProductType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>


    <attributeGroup name="SBOMAttrGrp">
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="spdx"></enumeration>
    				<enumeration value="cycloneDX"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="version" type="string"></attribute>
    	<attribute name="format">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="JSON"></enumeration>
    				<enumeration value="XML"></enumeration>
    				<enumeration value="TV"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="signature" type="string"></attribute>
    </attributeGroup>

    <complexType name="SBOMType">
    	<simpleContent>
    		<extension base="string">
    			<attributeGroup ref="SAG:SBOMAttrGrp"></attributeGroup>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== rjb4standards/REA-Products/SAGVendorSchemaSAG-PM.xml
<?xml version="1.0" encoding="UTF-8"?>
<SAG:VendorResponse xmlns:SAG="http://softwareassuranceguardian.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://softwareassuranceguardian.com/ SAGVendorSchema.xsd ">
  <SAG:VendorLegalName>Reliable Energy Analytics LLC</SAG:VendorLegalName>
  <SAG:SupplierID>dns:reliableenergyanalytics.com</SAG:SupplierID>
  <SAG:StreetAddress>23 Linda Drive</SAG:StreetAddress>
  <SAG:City>Westfield</SAG:City>
  <SAG:StateOrProvince>Massachusetts</SAG:StateOrProvince>
  <SAG:ZipCode>01085</SAG:ZipCode>
  <SAG:Country>USA</SAG:Country>
  <SAG:WebsiteURL>https://reliableenergyanalytics.com/</SAG:WebsiteURL>
  <SAG:ContactTelephone>978-696-1788</SAG:ContactTelephone>
  <SAG:ContactEmail>dick@reliableenergyanalytics.com</SAG:ContactEmail>
  <SAG:ContactPerson>Dick Brooks</SAG:ContactPerson>
  <SAG:DUNSNumber>REDACTED</SAG:DUNSNumber>
  <SAG:NAESBEIRID>REAL</SAG:NAESBEIRID>
  <SAG:CyberSecPolicyURL>https://softwareassuranceguardian.com/REDACTED</SAG:CyberSecPolicyURL>
  <SAG:FinancialDataURL>https://softwareassuranceguardian.com/REDACTED</SAG:FinancialDataURL>
  <SAG:CompanyDataURL>https://softwareassuranceguardian.com/REDACTED</SAG:CompanyDataURL>
  <SAG:Products>
    <SAG:Product>
      <SAG:LicensorName>Reliable Energy Analytics LLC</SAG:LicensorName>
      <SAG:ProductName>SAG-PM (TM)</SAG:ProductName>
      <SAG:Version>1.1.3</SAG:Version>
      <SAG:SBOM type="cycloneDX" version="1.2" format="XML" signature="https://softwareassuranceguardian.com/REDACTED">https://softwareassuranceguardian.com/REDACTED</SAG:SBOM>
      <SAG:SourceLocationURL>https://softwareassuranceguardian.com/REDACTED/REDACTED/</SAG:SourceLocationURL>
      <SAG:DigitallySigned>Y</SAG:DigitallySigned>
      <SAG:UnsolvedVulnerabilities>N</SAG:UnsolvedVulnerabilities>
      <SAG:SDLCPolicyURL>https://softwareassuranceguardian.com/REDACTED</SAG:SDLCPolicyURL>
      <SAG:SDLCEvidenceDataURL>https://softwareassuranceguardian.com/REDACTED</SAG:SDLCEvidenceDataURL>
      <SAG:CommercialStatus>Available</SAG:CommercialStatus>
      <SAG:SupportStatus>Supported</SAG:SupportStatus>
      <SAG:LastModifiedDateTimeUTC>2021-09-28T17:34:00</SAG:LastModifiedDateTimeUTC>
    </SAG:Product>
  </SAG:Products>
</SAG:VendorResponse>

=== rjb4standards/REA-Products/SAGVendorSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<SAG:VendorResponse xmlns:SAG="http://softwareassuranceguardian.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://softwareassuranceguardian.com/ SAGVendorSchema.xsd ">
  <SAG:VendorLegalName>SAG:VendorLegalName</SAG:VendorLegalName>
  <SAG:SupplierID>SAG:SupplierID</SAG:SupplierID>
  <SAG:StreetAddress>SAG:StreetAddress</SAG:StreetAddress>
  <SAG:City>SAG:City</SAG:City>
  <SAG:StateOrProvince>SAG:StateOrProvince</SAG:StateOrProvince>
  <SAG:ZipCode>SAG:ZipCode</SAG:ZipCode>
  <SAG:Country>SAG:Country</SAG:Country>
  <SAG:WebsiteURL>SAG:WebsiteURL</SAG:WebsiteURL>
  <SAG:ContactTelephone>SAG:ContactTelephone</SAG:ContactTelephone>
  <SAG:ContactEmail>SAG:ContactEmail</SAG:ContactEmail>
  <SAG:ContactPerson>SAG:ContactPerson</SAG:ContactPerson>
  <SAG:DUNSNumber>SAG:DUNSNumber</SAG:DUNSNumber>
  <SAG:NAESBEIRID>SAG:NAESBEIRID</SAG:NAESBEIRID>
  <SAG:Products>
    <SAG:Product>
      <SAG:LicensorName>SAG:LicensorName</SAG:LicensorName>
      <SAG:ProductName>SAG:ProductName</SAG:ProductName>
      <SAG:Version>SAG:Version</SAG:Version>
      <SAG:SBOM>SAG:SBOM</SAG:SBOM>
      <SAG:SourceLocationURL>SAG:SourceLocationURL</SAG:SourceLocationURL>
      <SAG:DigitallySigned>SAG:DigitallySigned</SAG:DigitallySigned>
      <SAG:UnsolvedVulnerabilities>SAG:UnsolvedVulnerabilities</SAG:UnsolvedVulnerabilities>
      <SAG:CommercialStatus>SAG:CommercialStatus</SAG:CommercialStatus>
      <SAG:SupportStatus>SAG:SupportStatus</SAG:SupportStatus>
      <SAG:LastModifiedDateTimeUTC>2001-12-31T12:00:00</SAG:LastModifiedDateTimeUTC>
    </SAG:Product>
  </SAG:Products>
</SAG:VendorResponse>

=== rjb4standards/REA-Products/CISA_VRFtemplate/CISA_VRFtemplate-SAGVendorSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Instructions for completing this VRF are available online at https://energycentral.com/c/pip/advice-software-vendors-prepare-omb-m-22-18-requirements -->
<!-- 
	Copyright and all other rights reserved by Reliable Energy Analytics, LLC (REA) 2018-2023. 
	Licensed under Creative Commons 4.0 https://creativecommons.org/licenses/by/4.0/
	
	GIFTED to the Internet Engineering Task Force Supply Chain Integrity, Transparency and Trust (IETF SCITT) work group on July 17, 2023
	
	A sample template for use by software producers to manage artifacts that may be required to satisfy CISA/OMB self attestation form processing
	is also available online at https://github.com/rjb4standards/REA-Products/tree/master/CISA_VRFtemplate   

DISCLAIMER OF WARRANTIES
TO THE EXTENT NOT PROHIBITED BY LAW, REA HEREBY DISCLAIMS ALL EXPRESS OR IMPLIED REPRESENTATIONS, 
WARRANTIES, GUARANTEES, AND CONDITIONS OF ANY KIND, ARISING BY LAW OR OTHERWISE, WITH REGARD TO THIS ARTIFACT, 
INCLUDING BUT NOT LIMITED TO REPRESENTATIONS, WARRANTIES, GUARANTEES, AND CONDITIONS OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, AND QUALITY OF SERVICE.
 
REA MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT, EFFECTIVENESS, USEFULNESS, RELIABILITY, 
AVAILABILITY, TIMELINESS, QUALITY, SUITABILITY, ACCURACY OR COMPLETENESS OF THIS ARTIFACT OR THE 
RESULTS YOU MAY OBTAIN BY USING THE ARTIFACT OR THAT THE ARTIFACT WILL BE ERROR-FREE.
	
--> 
<SAG:VendorResponse xmlns:SAG="http://softwareassuranceguardian.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://softwareassuranceguardian.com/ SAGVendorSchema.xsd ">
  <SAG:VendorLegalName>SAG:VendorLegalName</SAG:VendorLegalName>
  <SAG:SupplierID>SAG:SupplierID - SAM.gov UEI code</SAG:SupplierID>
  <SAG:StreetAddress>SAG:StreetAddress</SAG:StreetAddress>
  <SAG:City>SAG:City</SAG:City>
  <SAG:StateOrProvince>SAG:StateOrProvince</SAG:StateOrProvince>
  <SAG:ZipCode>SAG:ZipCode</SAG:ZipCode>
  <SAG:Country>SAG:Country</SAG:Country>
  <SAG:WebsiteURL>SAG:WebsiteURL</SAG:WebsiteURL>
  <SAG:ContactTelephone>SAG:ContactTelephone</SAG:ContactTelephone>
  <SAG:ContactEmail>SAG:ContactEmail</SAG:ContactEmail>
  <SAG:ContactPerson>SAG:ContactPerson</SAG:ContactPerson>
  <SAG:DUNSNumber>NOT NEEDED FOR CISA</SAG:DUNSNumber>
  <SAG:NAESBEIRID>NOT NEEDED FOR CISA</SAG:NAESBEIRID>
  <SAG:CyberSecPolicyURL>SAG:CyberSecPolicyURL</SAG:CyberSecPolicyURL>
  <SAG:FinancialDataURL>SAG:FinancialDataURL</SAG:FinancialDataURL>
  <SAG:CompanyDataURL>SAG:CompanyDataURL</SAG:CompanyDataURL>
  <SAG:Products>
    <SAG:Product>
      <SAG:LicensorName>Software Producer Legal Name per OMB M-22-18</SAG:LicensorName>
      <SAG:ProductName>SAG:ProductName</SAG:ProductName>
      <SAG:Version>SAG:Version</SAG:Version>
      <SAG:SBOM DigitalSignatureURL="" format="JSON" type="spdx" version="">SAG:SBOM</SAG:SBOM>
      <SAG:SourceLocationURL>SAG:SourceLocationURL</SAG:SourceLocationURL>
      <SAG:DigitallySigned>Y</SAG:DigitallySigned>
      <SAG:UnsolvedVulnerabilities>Y</SAG:UnsolvedVulnerabilities>
      <SAG:KnownVulnInfoURL DigitalSignatureURL="" DocFormat="Word">SAG:KnownVulnInfoURL</SAG:KnownVulnInfoURL>
      <SAG:SDLCPolicyURL>SAG:SDLCPolicyURL</SAG:SDLCPolicyURL>
      <SAG:SDLCEvidenceDataURL>SAG:SDLCEvidenceDataURL</SAG:SDLCEvidenceDataURL>
      <SAG:CyberSecLabelURL>SAG:CyberSecLabelURL URL to SAG-CTR Trusted Product Label Registry Entry - NOT NEEDED FOR CISA </SAG:CyberSecLabelURL>
      <SAG:CommercialStatus>Available</SAG:CommercialStatus>
      <SAG:SupportStatus>Supported</SAG:SupportStatus>
      <SAG:LastModifiedDateTimeUTC>2024-03-24T12:00:00</SAG:LastModifiedDateTimeUTC>
    </SAG:Product>
  </SAG:Products>
</SAG:VendorResponse>

=== rjb4standards/REA-Products/SAGVendorResponseSAMPLE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Copyright and all other rights reserved by Reliable Energy Analytics, LLC (REA) 2018-2022. 
DISCLAIMER OF WARRANTIES
TO THE EXTENT NOT PROHIBITED BY LAW, REA HEREBY DISCLAIMS ALL EXPRESS OR IMPLIED REPRESENTATIONS, 
WARRANTIES, GUARANTEES, AND CONDITIONS OF ANY KIND, ARISING BY LAW OR OTHERWISE, WITH REGARD TO THIS ARTIFACT, 
INCLUDING BUT NOT LIMITED TO REPRESENTATIONS, WARRANTIES, GUARANTEES, AND CONDITIONS OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, AND QUALITY OF SERVICE.
 
REA MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT, EFFECTIVENESS, USEFULNESS, RELIABILITY, 
AVAILABILITY, TIMELINESS, QUALITY, SUITABILITY, ACCURACY OR COMPLETENESS OF THIS ARTIFACT OR THE 
RESULTS YOU MAY OBTAIN BY USING THE ARTIFACT OR THAT THE ARTIFACT WILL BE ERROR-FREE.
	
--> 
<SAG:VendorResponse xmlns:SAG="http://softwareassuranceguardian.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://softwareassuranceguardian.com/ SAGVendorSchema.xsd ">
  <SAG:VendorLegalName>Reliable Energy Analytics LLC</SAG:VendorLegalName>
  <SAG:SupplierID>dns:reliableenergyanalytics.com</SAG:SupplierID>
  <SAG:StreetAddress>23 Linda Drive</SAG:StreetAddress>
  <SAG:City>Westfield</SAG:City>
  <SAG:StateOrProvince>Massachusetts</SAG:StateOrProvince>
  <SAG:ZipCode>01085</SAG:ZipCode>
  <SAG:Country>USA</SAG:Country>
  <SAG:WebsiteURL>https://reliableenergyanalytics.com/</SAG:WebsiteURL>
  <SAG:ContactTelephone>978-696-1788</SAG:ContactTelephone>
  <SAG:ContactEmail>dick@reliableenergyanalytics.com</SAG:ContactEmail>
  <SAG:ContactPerson>Dick Brooks</SAG:ContactPerson>
  <SAG:DUNSNumber>111509681</SAG:DUNSNumber>
  <SAG:NAESBEIRID>REAL</SAG:NAESBEIRID>
  <SAG:CyberSecPolicyURL>https://softwareassuranceguardian.com/CyberSecPolicy.html</SAG:CyberSecPolicyURL>
  <SAG:FinancialDataURL>https://softwareassuranceguardian.com/FinancialData.html</SAG:FinancialDataURL>
  <SAG:CompanyDataURL>https://softwareassuranceguardian.com/CompanyData.html</SAG:CompanyDataURL>
  <SAG:Products>
    <SAG:Product>
      <SAG:LicensorName>Reliable Energy Analytics LLC</SAG:LicensorName>
      <SAG:ProductName>SAG-PM (TM)</SAG:ProductName>
      <SAG:Version>1.2</SAG:Version>
      <SAG:SBOM type="cycloneDX" version="1.4" format="XML" DigitalSignatureURL="https://softwareassuranceguardian.com/SAG-PM_SBOM_V1_2.xml.sig">https://softwareassuranceguardian.com/SAG-PM_SBOM_V1_2.xml</SAG:SBOM>
      <SAG:SourceLocationURL>https://softwareassuranceguardian.com/sag-pm.zip</SAG:SourceLocationURL>
      <SAG:DigitallySigned>Y</SAG:DigitallySigned>
      <SAG:UnsolvedVulnerabilities>N</SAG:UnsolvedVulnerabilities>
      <SAG:KnownVulnInfoURL DocFormat="XML" DigitalSignatureURL="https://softwareassuranceguardian.com/SAG-PM_VulnDisclosure_V1_2.xml.sig">https://softwareassuranceguardian.com/SAG-PM_VulnDisclosure_V1_2.xml</SAG:KnownVulnInfoURL>
      <SAG:SDLCPolicyURL>https://softwareassuranceguardian.com/SAG-PM-V1_2_SDLC-POLICY-NIST.SP.800-218.SSDF-table.pdf</SAG:SDLCPolicyURL>
      <SAG:SDLCEvidenceDataURL>https://softwareassuranceguardian.com/SAG-PM_SDLCEvidenceData_V1_2.html</SAG:SDLCEvidenceDataURL>
	  <SAG:CyberSecLabelURL>https://softwareassuranceguardian.com/SAGCTR_inquiry/getSAGScore?FileHash=94EDB27E1995370E9003EE0A0A12D0A7DE2E8DA5EB663C31A97CB4215AB171B6</SAG:CyberSecLabelURL>
      <SAG:CommercialStatus>Available</SAG:CommercialStatus>
      <SAG:SupportStatus>Supported</SAG:SupportStatus>
      <SAG:LastModifiedDateTimeUTC>2022-09-22T16:23:00</SAG:LastModifiedDateTimeUTC>
    </SAG:Product>
  </SAG:Products>
</SAG:VendorResponse>
