=== rjb4standards/REA-Products/SAGVulnDisclosure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Legal Disclaimer

Copyright and all other rights reserved by Reliable Energy Analytics, LLC (REA) 2018-2021. 
Others are free to use this “boilerplate” template under the Creative Commons V4.0 license terms.

DISCLAIMER OF WARRANTIES
TO THE EXTENT NOT PROHIBITED BY LAW, REA HEREBY DISCLAIMS ALL EXPRESS OR IMPLIED REPRESENTATIONS, WARRANTIES, GUARANTEES, AND CONDITIONS OF ANY KIND, ARISING BY LAW OR OTHERWISE, WITH REGARD TO THIS ARTIFACT, INCLUDING BUT NOT LIMITED TO REPRESENTATIONS, WARRANTIES, GUARANTEES, AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, AND QUALITY OF SERVICE.
REA MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT, EFFECTIVENESS, USEFULNESS, RELIABILITY, AVAILABILITY, TIMELINESS, QUALITY, SUITABILITY, ACCURACY OR COMPLETENESS OF THIS ARTIFACT OR THE RESULTS YOU MAY OBTAIN BY USING THE ARTIFACT OR THAT THE ARTIFACT WILL BE ERROR-FREE.
 -->
<schema elementFormDefault="qualified" targetNamespace="http://softwareassuranceguardian.com/1_1_4" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SAG="http://softwareassuranceguardian.com/1_1_4">
	<element name="VulnerabilityDisclosure" type="SAG:VulnerabilityDisclosureType" ></element>

     <complexType name="VulnerabilityDisclosureType">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="Component" type="SAG:ComponentType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
        <attributeGroup ref="SAG:VulnDisclosureAttrGrp"></attributeGroup>
    </complexType>

    <complexType name="ComponentType">
    	<sequence>
    		<element name="CVE" type="SAG:CVEType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
        <attributeGroup ref="SAG:ComponentAttrGrp"></attributeGroup>
    </complexType>

    <complexType name="CVEType">
    	<sequence>
    		<element name="CVEID" type="string"></element>
    		<element name="CVSS" type="string"></element>
    		<element name="CVEDescription" type="string"></element>
    		<element name="FixStatus">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="N/A"></enumeration>
    					<enumeration value="Fix Available"></enumeration>
    					<enumeration value="Not Fixed"></enumeration>
    					<enumeration value="No Plans to Fix"></enumeration>
    					<enumeration value="Pending Development"></enumeration>
    					<enumeration value="In Development"></enumeration>
    					<enumeration value="In Test"></enumeration>
    					<enumeration value="Planned Fix this Year"></enumeration>
    					<enumeration value="Planned Future Fix"></enumeration>
    					<enumeration value="Investigating"></enumeration>
    					<enumeration value="Confirmed Issue"></enumeration>
    					<enumeration value="Unknown"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="AnalysisFindings" type="string"></element>
    	</sequence>
    </complexType>
    
    <attributeGroup name="VulnDisclosureAttrGrp">
    	<attribute name="SBOMAuthor" type="string"></attribute>
    	<attribute name="SBOMTimestamp" type="dateTime"></attribute>
    	<attribute name="SBOMLocation" type="string"></attribute>
    	<attribute name="SBOMFormat">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="SPDX"></enumeration>
    				<enumeration value="CycloneDX"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="SBOMFormatSyntax">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="TagValue"></enumeration>
    				<enumeration value="XML"></enumeration>
    				<enumeration value="JSON"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="SBOMTotalComponentCount" type="int"></attribute>
    	<attribute name="CVERespository" type="string"></attribute>
    	<attribute name="SupplierName" type="string"></attribute>
    	<attribute name="ProductName" type="string"></attribute>
    	<attribute name="ProductVersion" type="string"></attribute>
    	<attribute name="PackageSourceLocation" type="string"></attribute>
    	<attribute name="VulnDisclosureCreateDate" type="dateTime"></attribute>
    </attributeGroup>

    <attributeGroup name="ComponentAttrGrp">
    	<attribute name="ComponentSupplierName" type="string"></attribute>
    	<attribute name="ComponentName" type="string"></attribute>
    	<attribute name="ComponentVersion" type="string"></attribute>
    	<attribute name="ComponentID" type="string"></attribute>
    	<attribute name="CVESearchString" type="string"></attribute>
    	<attribute name="NumberVulnsReported" type="int"></attribute>
    </attributeGroup>
</schema>

=== rjb4standards/REA-Products/SAGVulnDisclosureSAG-PM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Copyright and all other rights reserved by Reliable Energy Analytics, LLC (REA) 2018-2021. 
	Licensed under Creative Commons 4.0 https://creativecommons.org/licenses/by/4.0/  

DISCLAIMER OF WARRANTIES
TO THE EXTENT NOT PROHIBITED BY LAW, REA HEREBY DISCLAIMS ALL EXPRESS OR IMPLIED REPRESENTATIONS, 
WARRANTIES, GUARANTEES, AND CONDITIONS OF ANY KIND, ARISING BY LAW OR OTHERWISE, WITH REGARD TO THIS ARTIFACT, 
INCLUDING BUT NOT LIMITED TO REPRESENTATIONS, WARRANTIES, GUARANTEES, AND CONDITIONS OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, AND QUALITY OF SERVICE.
 
REA MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT, EFFECTIVENESS, USEFULNESS, RELIABILITY, 
AVAILABILITY, TIMELINESS, QUALITY, SUITABILITY, ACCURACY OR COMPLETENESS OF THIS ARTIFACT OR THE 
RESULTS YOU MAY OBTAIN BY USING THE ARTIFACT OR THAT THE ARTIFACT WILL BE ERROR-FREE.
	
--> 
 <SAG:VulnerabilityDisclosure CVERespository="NIST_NVD" PackageSourceLocation="https://softwareassuranceguardian.com/REDACTED" ProductName="SAG-PM (TM)" ProductVersion="1.1.4" SBOMAuthor="Reliable Energy Analytics LLC" SBOMFormat="CycloneDX" SBOMFormatSyntax="XML" SBOMLocation="https://softwareassuranceguardian.com/REDACTED" SBOMTimestamp="2021-10-05T22:04:00Z" SBOMTotalComponentCount="86" SupplierName="Reliable Energy Analytics LLC" VulnDisclosureCreateDate="2021-10-23T15:30:00" xmlns:SAG="http://softwareassuranceguardian.com/1_1_4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://softwareassuranceguardian.com/1_1_4 SAGVulnDisclosure.xsd ">
	<SAG:Component CVESearchString="https://services.nvd.nist.gov/rest/json/cves/1.0?keyword=SAG-PM+(TM)+1.1.4" ComponentID="" ComponentName="SAG-PM (TM)" ComponentSupplierName="Reliable Energy Analytics LLC" ComponentVersion="1.1.4" NumberVulnsReported="0"/>
	<SAG:Component CVESearchString="https://services.nvd.nist.gov/rest/json/cves/1.0?keyword=SAG-PM.msi+1.1.4" ComponentID="" ComponentName="SAG-PM.msi" ComponentSupplierName="Reliable Energy Analytics LLC" ComponentVersion="1.1.4" NumberVulnsReported="0"/>
	<SAG:Component CVESearchString="https://services.nvd.nist.gov/rest/json/cves/1.0?keyword=SAG-PM.exe+1.1.4" ComponentID="" ComponentName="SAG-PM.exe" ComponentSupplierName="Reliable Energy Analytics LLC" ComponentVersion="1.1.4" NumberVulnsReported="0"/>
	<SAG:Component CVESearchString="https://services.nvd.nist.gov/rest/json/cves/1.0?keyword=END+USER+LICENSE+AGREEMENT.rtf+1.1.4" ComponentID="" ComponentName="END USER LICENSE AGREEMENT.rtf" ComponentSupplierName="Reliable Energy Analytics LLC" ComponentVersion="1.1.4" NumberVulnsReported="0"/>
	<SAG:Component CVESearchString="https://services.nvd.nist.gov/rest/json/cves/1.0?keyword=cryptography+3.3.1" ComponentID="0e85aaae861d0485eb5a79d33226dd6248d2a9f133b81532c8f5aae37de10ff7" ComponentName="cryptography" ComponentSupplierName="The cryptography developers" ComponentVersion="3.3.1" NumberVulnsReported="2">
		<SAG:CVE>
      			<SAG:CVEID>CVE-2020-36242</SAG:CVEID>
      			<SAG:CVSS>9.1</SAG:CVSS>
      			<SAG:CVEDescription>In the cryptography package before 3.3.2 for Python, certain sequences of update calls to symmetrically encrypt multi-GB values could result in an integer overflow and buffer overflow, as demonstrated by the Fernet class.</SAG:CVEDescription>
      			<SAG:FixStatus>N/A</SAG:FixStatus>
      			<SAG:AnalysisFindings>This vulnerability is exploited during file encryption. SAG-PM does not perform file encryption using this component and is most likely not vulnerable to this CVE</SAG:AnalysisFindings>
    		</SAG:CVE>
    		<SAG:CVE>
      			<SAG:CVEID>CVE-2014-8564</SAG:CVEID>
      			<SAG:CVSS>5.0</SAG:CVSS>
      			<SAG:CVEDescription>The _gnutls_ecc_ansi_x963_export function in gnutls_ecc.c in GnuTLS 3.x before 3.1.28, 3.2.x before 3.2.20, and 3.3.x before 3.3.10 allows remote attackers to cause a denial of service (out-of-bounds write) via a crafted (1) Elliptic Curve Cryptography (ECC) certificate or (2) certificate signing requests (CSR), related to generating key IDs.</SAG:CVEDescription>
      			<SAG:FixStatus>N/A</SAG:FixStatus>
      			<SAG:AnalysisFindings>This vulnerability is exploited when Elliptic curve certificates are used. SAG-PM does not perform any elliptic curve certificate functions from this component and is most likely not vulnerable to this CVE</SAG:AnalysisFindings>
    		</SAG:CVE>
  	</SAG:Component>
<!--  Remaining components snipped for brevity. -->
</SAG:VulnerabilityDisclosure>
